[build]
    base = "/"
    publish = "public"
    command = "hugo --gc --minify"

[build.environment]
    HUGO_VERSION = "0.72.0"
    HUGO_ENABLEGITINFO = "true"

# Opt out of Google FLoC.
# https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
